name: "Run tests for s390x architecture"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: "Python 2.7"
            python-version: '2.7'
            toxenv: "py27"
          - name: "Pypy 2.7"
            python-version: 'pypy-2.7'
            toxenv: 'pypy'
          - name: "Python 3.7"
            python-version: '3.7'
            toxenv: 'py37'
          - name: "Pypy 3.7"
            python-version: 'pypy-3.7'
            toxenv: 'pypy3'
          - name: "Python 3.8"
            python-version: '3.8'
            toxenv: 'py38'
          - name: "Python 3.9"
            python-version: '3.9'
            toxenv: 'py39'
          - name: "Python 3.10"
            python-version: '3.10'
            toxenv: 'py310'
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: s390x
          distro: ubuntu20.04          
          python-version: ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          run: | 
            python -v
