name: "Run tests for s390x architecture"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    
    strategy:
      matrix:
        include:
          - name: "Python 2.7"
            python-version: '2.7'
            toxenv: "py27"
            
    steps :
    - name: Run build 
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        arch: s390x
        distro: ubuntu18.04
        python-version: ${{ matrix.python-version }}
    - name: Install Dependecies 
      uses: uraimo/run-on-arch-action@v2.0.9
      with:
        arch: s390x
        distro: ubuntu18.04
        run : |
          python -m pip install --upgrade pip 'setuptools<58' --force-reinstall
          pip install 'tox<4' tox-gh-actions flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Tests with tox
      env:
          TOXENV: ${{ matrix.toxenv }}
      with:
        arch: s390x
        distro: ubuntu18.04
        run: |
          tox
