name: "Run tests for s390x architecture"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 2.7  
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: s390x
          distro: ubuntu18.04
          run: |
            apt-get update
            apt-get install sudo 
            sudo apt-get install python2.7 git -y
            sudo apt-get install python-pip -y
            python2.7 -m pip install --upgrade pip 'setuptools<58' --force-reinstall
            pip install 'tox<4' tox-gh-actions flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            tox
