name: "Run python3.10 tests for s390x architecture"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10  
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: s390x
          distro: ubuntu-latest
          run: |
            apt-get update
            cat /etc/os-release 

