name: "Run python3.6 tests for s390x architecture"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6  
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: s390x
          distro: ubuntu18.04
          run: |
            apt-get update
            apt-get install sudo 
            sudo apt-get install python3 curl -y
            sudo apt-get install python3-pip build-essential libssl-dev libffi-dev python3-dev cargo -y
            python3 -m pip install --upgrade pip 'setuptools<58' --force-reinstall
            pip3 install 'tox<4' tox-gh-actions flake8 pytest
            if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            curl https://sh.rustup.rs -sSf | sh
            tox -e py36
