name: "Run tests for s390x architecture"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8 and run tests with TOX
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: s390x
          distro: ubuntu20.04
          install: |
            apt-get update
            apt-get install curl git wget -y
            apt-get install python3 -y
            apt-get install python3-pip libssl-dev libffi-dev python3-dev cargo -y      
          run: |
            python3 -m pip install --upgrade pip 'setuptools<58' --force-reinstall
            pip3 install 'tox<4' tox-gh-actions flake8 pytest
            if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            curl -o rustup.sh https://sh.rustup.rs
            bash rustup.sh -y
            tox -e py38
