name: "Run tests for s390x architecture"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - name: "Python 3.10"
            python-version: '3.10'
            toxenv: 'py310'
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: s390x
          distro: ubuntu20.04
          run: |
            apt-get update
            apt-get install sudo 
            sudo apt-get install curl git cargo -y
            python3 -m pip install --upgrade pip 'setuptools<58' --force-reinstall
            pip install 'tox<4' tox-gh-actions flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            curl -o rustup.sh https://sh.rustup.rs
            sudo bash rustup.sh -y
            tox -e ${{ matrix.toxenv }}
      - name: Linting
        if: ${{ matrix.python-version==3.10 }}
        env:
          TOXENV: lint
        run: |
          tox
      - name: Run Codecov
        if: ${{ matrix.python-version==3.10 }}
        env:
          TOXENV: lint
        run: |
          pip install codecov
          codecov
      - name: Upload coverage to Codecov
        if: ${{ matrix.python-version==3.10 }}
        uses: codecov/codecov-action@v1
