name: "Run tests for s390x architecture"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - name: "Python 2.7"
            python-version: '2.7'
            toxenv: "py27"
          - name: "Pypy 2.7"
            python-version: 'pypy-2.7'
            toxenv: 'pypy'
          - name: "Python 3.7"
            python-version: '3.7'
            toxenv: 'py37'
          - name: "Pypy 3.7"
            python-version: 'pypy-3.7'
            toxenv: 'pypy3'
          - name: "Python 3.8"
            python-version: '3.8'
            toxenv: 'py38'
          - name: "Python 3.9"
            python-version: '3.9'
            toxenv: 'py39'
          - name: "Python 3.10"
            python-version: '3.10'
            toxenv: 'py310'
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: s390x
          distro: ubuntu20.04
          run: |
            apt-get update
            apt-get install sudo 
            sudo apt-get install curl git cargo -y
            python3 -m pip install --upgrade pip 'setuptools<58' --force-reinstall
            pip3 install 'tox<4' tox-gh-actions flake8 pytest
            if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            curl -o rustup.sh https://sh.rustup.rs
            sudo bash rustup.sh -y
            tox -e ${{ matrix.toxenv }}
